baseurl         = "https://www.intelwalk.com"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 10
#SectionPagesMenu = "main"

[params]
  title       = "Intelwalk's Compendium of Intelligence and Nonsense"
  subtitle    = "All You'll Need To Know"

  cover       = "img/blog-cover.jpg"
  description = "Intelwalk's Development, Fantasy Football, and Business Blog"
  metaDescription = "Intelwalk's Development, Fantasy Football, and Business Blog"
  googleAnalytics = "UA-51054849-1"
  customCSS = []
  RSSLink = ""

  twitterName = "intelwalk"
  #fbName = "none"
  githubName = "intelwalk"

  logo = ""
  orgName = ""
  orgWebsite = ""
  orgDescription = ""

  author = "Intelwalk"
  authorAvatar = "img/profilepic.jpeg"#PROFILE PIC
  authorLocation = "Alabama"
  authorWebsite = "https://www.intelwalk.com"
  authorDescription = "Father, Husband, IT Manager, Coder, and Potential Lunch Winner"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 400

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Python"
  url = "/tags/python/"
  weight = 99

[[menu.main]]
  name = "Projects"
  url = "/categories/projects/"
  weight = 98